language: ruby
rvm:
  - 2.7.1
install:
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -P ~/
  - tar xvzf ~/geckodriver-v0.26.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.26.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share/
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bin/rails assets:precompile
script:
  - RAILS_ENV=test bin/rails db:migrate --trace
  - bin/rails db:test:prepare
  - bin/rails test
  - bin/rails test:system
before_script:
  - mysql -u root -e "create database questioncove_test;create user 'qcuser'@'%';grant all privileges on questioncove_test.* to 'qcuser'@'%';"
after_success:
  - bundle exec codeclimate-test-reporter
dist: trusty
sudo: required
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  code_climate:
    repo_token: 587ff98ac48f05453f6d4b6f2f2e6ad0aba2faaadaf52b7dbb15876d2aeda1fa
